# Generated by Django 3.1 on 2020-08-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookPublication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='votes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
